<#
.SYNOPSIS
    SOAR-lite YARA malware triage playbook.

.DESCRIPTION
    Creates a case folder, collects file hash and host evidence, copies the suspicious
    test file to quarantine, and generates a Markdown report.

.NOTES
    Lab-safe default: this script copies files to quarantine and does not delete originals.
#>

[CmdletBinding()]
param(
    [string]$FilePath = "C:\Wazuh-Test\evil.txt",
    [string]$RuleId = "100302",
    [string]$RootPath = "C:\Wazuh-SOAR",
    [switch]$DeleteOriginal
)

function New-CaseFolder {
    param(
        [string]$CaseType,
        [string]$RootPath
    )

    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $caseId = "CASE-$timestamp-$CaseType"
    $caseRoot = Join-Path $RootPath "Cases"
    $casePath = Join-Path $caseRoot $caseId
    New-Item -Path $casePath -ItemType Directory -Force | Out-Null
    return $casePath
}

function Write-CaseLog {
    param(
        [string]$CasePath,
        [string]$Message
    )

    $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Message
    Add-Content -Path (Join-Path $CasePath "case-log.txt") -Value $line
}

function Save-HostEvidence {
    param([string]$CasePath)

    Get-ComputerInfo -Property CsName,WindowsProductName,WindowsVersion,OsArchitecture |
        Out-File -FilePath (Join-Path $CasePath "host-info.txt") -Encoding UTF8

    Get-Process | Sort-Object ProcessName |
        Select-Object ProcessName,Id,Path -ErrorAction SilentlyContinue |
        Out-File -FilePath (Join-Path $CasePath "process-list.txt") -Encoding UTF8
}

New-Item -Path (Join-Path $RootPath "Cases") -ItemType Directory -Force | Out-Null
New-Item -Path (Join-Path $RootPath "Quarantine") -ItemType Directory -Force | Out-Null

$casePath = New-CaseFolder -CaseType "YARA" -RootPath $RootPath
Write-CaseLog -CasePath $casePath -Message "Started YARA malware triage playbook."
Write-CaseLog -CasePath $casePath -Message "Rule ID: $RuleId"
Write-CaseLog -CasePath $casePath -Message "File path: $FilePath"

Save-HostEvidence -CasePath $casePath

$fileExists = Test-Path $FilePath
$hashValue = "N/A"
$quarantinePath = "N/A"
$actionTaken = "No file action taken. File was not found."

if ($fileExists) {
    try {
        $hashValue = (Get-FileHash -Path $FilePath -Algorithm SHA256).Hash
        $fileName = Split-Path $FilePath -Leaf
        $quarantineName = "{0}-{1}" -f (Get-Date -Format "yyyyMMdd-HHmmss"), $fileName
        $quarantinePath = Join-Path (Join-Path $RootPath "Quarantine") $quarantineName

        Copy-Item -Path $FilePath -Destination $quarantinePath -Force
        $actionTaken = "Copied suspicious test file to quarantine. Original left in place."

        if ($DeleteOriginal) {
            Remove-Item -Path $FilePath -Force
            $actionTaken = "Copied file to quarantine and deleted original. Lab-only action."
        }

        Write-CaseLog -CasePath $casePath -Message "SHA256: $hashValue"
        Write-CaseLog -CasePath $casePath -Message "Quarantine path: $quarantinePath"
        Write-CaseLog -CasePath $casePath -Message "Action taken: $actionTaken"
    }
    catch {
        $actionTaken = "Error during file handling: $($_.Exception.Message)"
        Write-CaseLog -CasePath $casePath -Message $actionTaken
    }
}
else {
    Write-CaseLog -CasePath $casePath -Message "File not found. Evidence collection limited."
}

$report = @"
# YARA Malware Triage Incident Report

## Summary

A Wazuh/YARA-style alert was reviewed using the PowerShell SOAR-lite YARA playbook.

## Case Details

| Field | Value |
|---|---|
| Case Folder | $casePath |
| Rule ID | $RuleId |
| Hostname | $env:COMPUTERNAME |
| User | $env:USERNAME |
| Matched File | $FilePath |
| File Exists | $fileExists |
| SHA256 | $hashValue |
| Quarantine Path | $quarantinePath |
| Action Taken | $actionTaken |
| Timestamp | $(Get-Date -Format "yyyy-MM-dd HH:mm:ss") |

## Analyst Notes

- Confirm whether the YARA match was generated by a known lab test file.
- If this was unexpected, preserve the file and escalate for malware analysis.
- Attach Wazuh alert screenshot and YARA rule screenshot if available.

## Closure Recommendation

Close as lab validation if this was a simulated detection. Escalate if the file was unexpected or found outside the lab path.
"@

$reportPath = Join-Path $casePath "incident-report.md"
$report | Out-File -FilePath $reportPath -Encoding UTF8

Write-Host ""
Write-Host "YARA playbook complete." -ForegroundColor Green
Write-Host "Case folder: $casePath"
Write-Host "Report: $reportPath"
